---
dataset:
  shuffle_data: True
  add_eos: True
  training:
    data_root: '/kaggle/input/coco-textcaps-textvqa/tran_val_dataset/images'
    csv_file: '/kaggle/input/coco-textcaps-textvqa/train_caps_vqa.csv'
  validation:
    data_root: '/kaggle/input/coco-textcaps-textvqa/tran_val_dataset/images'
    csv_file: '/kaggle/input/coco-textcaps-textvqa/val_caps_vqa.csv'
  testing:
    data_root: '...'
    csv_file: '...'

hyperparams:
  image_size: [224, 224]
  encoder_input_tokens: 50
  decoder_input_tokens: 50
  decoder_target_tokens: 50
  optimizer_name: adafactor
  learning_rate: 0.001
  clipping_threshold: 1.0
  train_batch_size: 64
  val_batch_size: 64
  save_best: False
  num_steps: 50000000
  save_steps: 2000
  val_steps: 100
  freeze_vit: False

checkpoints_dir:
  save_state: '/kaggle/working'
  save_params: '/kaggle/working'
  save_history: '/kaggle/working'
  load_params: '...'
  load_opt: '...'
  load_state: '...'

t5:
  gin_file: 'models/t5x/t5x/examples/t5/t5_1_1/base.gin'
  dropout_rate: 0.1
  vit_patches_embs_size: 50
  pretrained_path: '/kaggle/working/pali-model/pretrained/flan_t5_base'
  vocab_size: 32128

vit:
  num_classes: null
  model_name: 'ViT-B_32'
  classifier: "token_unpooled"
  pretrained_path: '../pretrained/ViT-B_32.npz'